### ISSUE TITLE
Setting database collation

### ISSUE THREAD

**Issue by alexbowers-tecmark** [robmorgan/phinx#463]
I can't seem to find the way to set the table and database collation and charset.

How can i go about this?

**Comment by RQuadling** [comment]
In my ```phinx.yaml``` file I have ...

```
    development:
        adapter: mysql
        host: localhost
        name: aaaaaaaaaaaa
        user: bbbbbbbbbb
        pass: cccccccccc
        port: 3306
        charset: utf8
        collation: utf8_unicode_ci
```
