### ISSUE TITLE
Where do we save custom migration base classes?

### ISSUE THREAD

**Issue by reloaded** [robmorgan/phinx#556]
I've integrated Phinx into my project using Composer and i'm not sure where I need to include the custom migration base class so Phinx can auto-include it.

Here's my project structure:

mysql_host1_migrations/
mysql_host2_migrations/
vendor/
composer.json
composer.lock
mysql_host1.yml
mysql_host2.yml

**Comment by rquadling** [comment]
Wherever you want, just as long as they are auto-loadable.

My migration template creation classes are in my lib and my lib is PSR-4 compliant and the root is in my composer.json.

```
...
  "autoload": {
    "psr-0": {
      "DigiTickets": "lib/",
      "Omnipay": "lib/"
    },
    "classmap": [
      "classes/"
    ]
  },
...
```

And so, ```[project root]/lib/DigiTickets/Migrations/Templates/ByDirectory.php```, ```[project root]/lib/DigiTickets/Migrations/Templates/ByDirection.php```, ```[project root]/lib/DigiTickets/Migrations/Templates/Permission.php```, etc. are all available via autoloading.

I also extended this to be able to set up aliases in the yaml file (https://github.com/rquadling/phinx/tree/feature/AliasesForCreationTemplateClasses). Waiting on this to be accepted/merged.

My ```phinx.yml``` contains ...

```
aliases:
    byDirection: DigiTickets\Migration\Phinx\ByDirection
    byDirectory: DigiTickets\Migration\Phinx\ByDirectory
    Permission: DigiTickets\Migration\Phinx\Permission
```

So, all I need to do is ```vendor/bin/phinx create NewPermissionForTableX -l Permission``` and I get a new permission style migration ready for me to populate the elements needed.
