### ISSUE TITLE
Skeleton dropped up/down methods

### ISSUE THREAD

**Issue by khjohnson1972** [robmorgan/phinx#648]
The "create" command no longer includes the up/down method in the skeleton. It only creates the "change" method.

**Comment by rquadling** [comment]
That is correct. It is a change to the system. If you want to use your own template, then you have several options.

1. Use ```--template``` to nominate your own template on a per create basis.
2. Add a ```templates:file:``` entry to your config file (normally ```phinx.yml```).

An example from my setup.

```
migration_base_class: MyProject\Migration\AbstractMigration
templates:
    file: ./lib/MyProject/Migration/Phinx/Templates/MyProject.template

aliases:
    byDirection: MyProject\Migration\Phinx\ByDirection
    byDirectory: MyProject\Migration\Phinx\ByDirectory
    Permission: MyProject\Migration\Phinx\Permission
    copyPermission: MyProject\Migration\Phinx\CopyPermission
```

I use an alternative abstract migration class - it extends the Phinx one.
I also use an alternative template - it reinstates ```up()```/```down()``` and has the new documentation regarding ```change()```.
And I have 4 aliases for alternative template creation,

Hope this helps.
