### ISSUE TITLE
Feature Request: custom data types

### ISSUE THREAD

**Issue by bradynpoulsen** [robmorgan/phinx#753]
I think it would be really useful to have a way to add a custom column name data type when using `addColumn()`. This would then make it so it could be aliased to an actual data type. 

For example with MySQL,

*without custom type*
```php
$table->addColumn('id', 'binary', ['limit' => 16]); // uuid v4
```

*with custom type*
```php
$table->addColumn('id', 'uuid');
```

**Comment by bradynpoulsen** [comment]
Here is a possible flow:
- [ ] 1. Register `'uuid'` to my `UuidCustomType` class that implements `CustomTypeInterface` via
    - [ ] a. YAML entry
    - [ ] b. Inside a custom migration base class on construct
- [ ] 2. Implement `UuidCustomType` that aliases to the real `'binary'` type with `['limit' => 16]`

**Comment by twoixter** [comment]
@bradynpoulsen This is actually something I was thinking about implementing. This semantic is very much like a User Defined Type or a Data Domain. I was skeptical at first because each database has a concept of UDT or Domain (E.G: [Check constraints](https://en.wikipedia.org/wiki/Check_constraint) and UDT in SQL Server) and AFAIK, don't supported in migrations. My concern was that if implemented, it would give the impression to extend the user defined type to the DB Adapter.

This is my suggestion for the flow. If interested, I might create a fork and start developing:

** Define a new "domain" for our data types in the phinx.yml configuration**

```yaml
# Domain defined in the config phinx.ml
# This would start a "domain" for our data types
domain:
    phone:    # New user defined data type name
        type: string   # Based on this base phinx data type
        options:       # With these options.
            length: 9
            null: true
    short_status:
        type: enum
        values: pending, started, finished
```

The intention is to use those as new data types, and they'd just use the values for `type` and `options`.

```php
    // Use our user defined types from config
    $table->addColumn("phone_number", "phone");
    $table->addColumn("task_status", "short_status");
```

Since those are really just aliases for the type and options, we could just add new options to override:

```php
    // Use our user defined types from config
    $table->addColumn("mobile_number", "phone", array("length" => 12, "null" => false));
```

Let me know what do you think.
